apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: trust-manager
    releaseName: trust-manager
    version: v0.21.1
    repo: oci://quay.io/jetstack/charts
    namespace: cert-manager-operator
